---
profile::openstack::volume::type:
  rbd:
    visibility: "public"
    properties:
      - 'volume_backend_name=rbd-volumes'
  mass-storage-default:
    visibility: "private"
    properties:
      - 'volume_backend_name=mass-storage-default'

profile::openstack::volume::backend::rbd:
  rbd-volumes:
    rbd_pool: 'volumes'
    rbd_user: 'cinder'
    rbd_flatten_volume_from_snapshot: 'True'
    rbd_secret_uuid: "%{hiera('libvirt_rbd_secret_uuid')}"
    extra_options:
      rbd-volumes/enable_deferred_deletion:
        value: 'True'
      rbd-volumes/rbd_exclusive_cinder_pool:
        value: 'True'
  mass-storage-default:
    rbd_pool: 'volumes_hdd_ec_meta'
    rbd_user: 'cinder-hdd-ec'
    rbd_flatten_volume_from_snapshot: 'True'
    rbd_secret_uuid: "%{hiera('libvirt_rbd_secret_uuid')}"
    extra_options:
      mass-storage-default/enable_deferred_deletion:
        value: 'True'
      mass-storage-default/rbd_exclusive_cinder_pool:
        value: 'True'

cinder::api::default_volume_type: 'rbd'

cinder::backends::enabled_backends:
  - rbd-volumes
  - mass-storage-default
