---
profile::openstack::volume::type:
  rbd:
    visibility: "public"
    properties:
      - 'volume_backend_name=rbd-volumes'
  mass-storage-default:
    visibility: "private"
    properties:
      - 'volume_backend_name=mass-storage-default'
  mass-storage-dcache:
    visibility: "private"
    properties:
      - 'volume_backend_name=mass-storage-dcache'
  mass-storage-dcache8:
    visibility: "private"
    properties:
      - 'volume_backend_name=mass-storage-dcache8'

profile::openstack::volume::backend::rbd:
  rbd-volumes:
    rbd_pool: 'volumes'
    rbd_user: 'cinder'
    rbd_flatten_volume_from_snapshot: 'True'
    rbd_secret_uuid: "%{hiera('libvirt_rbd_secret_uuid')}"
  mass-storage-default:
    rbd_pool: 'volumes_hdd_ec_meta'
    rbd_user: 'cinder-hdd-ec'
    rbd_flatten_volume_from_snapshot: 'True'
    rbd_secret_uuid: "%{hiera('libvirt_rbd_secret_uuid')}"
  mass-storage-dcache:
    rbd_pool: 'dcache_hdd_ec_meta'
    rbd_user: 'cinder-dcache-hdd-ec'
    rbd_flatten_volume_from_snapshot: 'True'
    rbd_secret_uuid: "%{hiera('libvirt_rbd_secret_uuid')}"
  mass-storage-dcache8:
    rbd_pool: 'dcache_hdd_ec_meta8'
    rbd_user: 'cinder-dcache-hdd-ec8'
    rbd_flatten_volume_from_snapshot: 'True'
    rbd_secret_uuid: "%{hiera('libvirt_rbd_secret_uuid')}"

cinder::api::default_volume_type: 'rbd'

cinder::backends::enabled_backends:
  - rbd-volumes
  - mass-storage-default
  - mass-storage-dcache
  - mass-storage-dcache8
